[workspace]

members =  [
    "d1p1", "d1p2",
    "d2p1", "d2p2",
    "d3p1", "d3p2",
    "d4p1", "d4p2",
    "day5",
    "day6",
    "day7",
    "day8",
    "day9",
    "day10",
    "day11",
    "day12"
]